apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 138778713921.dkr.ecr.ap-northeast-2.amazonaws.com/store-app
  newName: 138778713921.dkr.ecr.ap-northeast-2.amazonaws.com/store-app
  newTag: abcdefg
resources:
- ../../base
patchesStrategicMerge:
- store-deployment-patch.yaml
